### ISSUE TITLE
default atm and ld_func raise confusing error message in legacy backend

### ISSUE THREAD

**Issue by kecnry** [phoebe-project/phoebe2#313]
```
import phoebe

b = phoebe.default_binary()

b.add_dataset('lc')
b.add_compute('legacy')
b.run_compute(kind='legacy')
```

raises the following error:
```
Traceback (most recent call last):
  File "test_58.py", line 11, in <module>
    b.run_compute(kind='legacy')
  File "/home/kyle/.local/lib/python2.7/site-packages/phoebe/parameters/parameters.py", line 203, in _send_if_client
    return fctn(self, *args, **kwargs)
  File "/home/kyle/.local/lib/python2.7/site-packages/phoebe/frontend/bundle.py", line 3077, in run_compute
    raise ValueError("system failed to pass checks: {}".format(msg))
ValueError: system failed to pass checks: ld_func='interp' only supported by atm='ck2004'.  Either change atm@primary or ld_func@primary@lc01
```

when ck2004 isn't even an option for atm@legacy (and is set to extern_atmx by default).  

```
>>> print b['atm']
ParameterSet: 4 parameters
    atm@primary@phoebe01@compute: ck2004
  atm@secondary@phoebe01@compute: ck2004
    atm@primary@legacy01@compute: extern_atmx
  atm@secondary@legacy01@compute: extern_atmx
>>> print b['ld_func']
ParameterSet: 2 parameters
    ld_func@primary@lc01@dataset: interp
  ld_func@secondary@lc01@dataset: interp
```

We probably need to detect this case and raise a more helpful message, and also may need to allow b.run_checks to take a compute label as a kwarg... as this scenario above should pass tests for the phoebe-backend but not the legacy-backend.

**Comment by kecnry** [comment]
error/warning message will now say one of the following, depending on if atm='ck2004' is a valid option for the given set of compute options/backend:

* ld_func='interp' only supported by atm='ck2004'.  Either change atm@primary@phoebe01 or ld_func@primary@lc01.
* ld_func='interp' not supported by 'legacy' backend used by compute='legacy01'.  Change ld_func@primary@lc01 or use a backend that supports atm='ck2004'.
