### ISSUE TITLE
rotstar resulting in nans for Teffs

### ISSUE THREAD

**Issue by AstroNeel98** [phoebe-project/phoebe2#467]
I was trying out the tutorial of building sun on my local system. (windows PC, with PyCharm IDLE).

while executing the line 

`b.run_compute(irrad_method='none', distortion_method='rotstar')`

I encounter the following error
`on, 14 Jun 2021 11:43 UNIVERSE     WARNING Atmosphere parameters out of bounds: Teff=[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan], logg=[4.43807412 4.43807374 4.43807374 4.43807374 4.43807374 4.43807374
 4.43807374 4.43807301 4.43807266 4.43807301 4.43807302 4.43807266
 4.43807162 4.43807162 4.43807163 4.43807094 4.43806965 4.43806998
 4.43806967 4.43807098 4.43807164 4.43806877 4.43806972 4.43807005
 4.4380717  4.4380727  4.43807302 4.43807101 4.43807167 4.43806976
 4.43806881 4.43806975 4.43806799 4.43806739 4.43806797 4.43806736
 4.43806552 4.43806583 4.4380656  4.43806344 4.43806346 4.43806313
 4.43806505 4.43806652 4.43806751 4.43806385 4.43806506 4.43806241
 4.43806122 4.43806248 4.43806076 4.43805989 4.43806124 4.4380613
 4.43805924 4.43805899 4.43805852 4.43805773 4.43805897 4.43806008
 4.43805716 4.43805664 4.43805749 4.43805601 4.43805569 4.43805788
 4.43805628 4.43805965 4.4380615  4.4380633  4.438065   4.43806647
 4.43806744 4.43806792 4.43806788 4.43806115 4.4380593  4.43805774
 4.43805639 4.43806277 4.43806411 4.43806517 4.43806573 4.43806582
 4.43805772 4.43805628 4.43805919 4.43806065 4.43806195 4.43806291
 4.43806357 4.43806375 4.43805863 4.43805724 4.43805614 4.4380599
 4.43806089 4.43806149 4.43806179 4.43806434 4.43806195 4.43806624
 4.43806773 4.43806892 4.43806974 4.43806569 4.43806381 4.43806201
 4.43806694 4.43806768 4.43805937 4.43805855 4.43805985 4.43806004
 4.43805771 4.43805672 4.43805999 4.43805576 4.43806211 4.43806002
 4.43806374 4.43806492 4.43806573 4.43806272 4.4380612  4.43805974
 4.43806368 4.43805506 4.43805524 4.43805533 4.43805534 4.43805521
 4.43805502 4.43805689 4.43805605 4.43805539 4.43805758 4.43805487
 4.43805799 4.43805829 4.43805835 4.43805821 4.43805809 4.43805954
 4.43805787 4.43806083 4.43806166 4.43805963 4.43805852 4.43805746
 4.43805642 4.43805595 4.43805549 4.43805499 4.43805472 4.43805672
 4.4380569  4.43805687 4.43805668 4.43805653 4.43805627 4.43805717
 4.43805601 4.43805505 4.43805475 4.43805536 4.43805465 4.43805555
 4.43805571 4.43805578 4.43805556 4.43805536 4.43805539 4.43805521
 4.43805488 4.43805498 4.43805493 4.43805483 4.43805465 4.43805474
 4.4380549  4.43805471 4.43805473 4.43805466 4.43805465 4.43805469
 4.43805467 4.43805467 4.43805478 4.43805498 4.43805486 4.43805481
 4.43805519 4.43805526 4.4380556  4.43805502 4.43805556 4.43805474
 4.4380564  4.43805479 4.43805466 4.43805529 4.43805611 4.43805744
 4.43806137 4.43805933 4.43806355 4.43806567 4.43806757 4.43806993
 4.43807169 4.43807269 4.43807302 4.43806794 4.43806587 4.43806964
 4.43807109 4.4380717  4.43806372 4.43806181 4.4380667  4.43806457
 4.43806269 4.43806129 4.43805954 4.4380576  4.43805601 4.43805512
 4.4380547  4.4380693  4.43806766 4.43806998 4.43806499 4.43806804
 4.43806687 4.43806078 4.43805912 4.43805763 4.43806224 4.43806382
 4.43805614 4.43805507 4.43805467 4.43806528 4.43805473 4.43805478
 4.43805514 4.43805547 4.43805609 4.43805702 4.43805524 4.43805557
 4.43805632 4.43805688 4.4380578  4.43805469 4.43805514 4.43805468
 4.438055   4.43805609 4.4380577  4.43805914 4.43806033 4.43806145
 4.43806246 4.43805773 4.43805883 4.43805687 4.43805618 4.43805469
 4.43805512 4.43805615 4.43805743 4.4380579  4.43805883 4.43805992
 4.43805509 4.43805468 4.43805605 4.43805764 4.43805887 4.43805972
 4.43806044 4.43805477 4.4380552  4.43805608 4.43805758 4.43805479
 4.43805467 4.43805503 4.43805553 4.43805718 4.4380557  4.43805667
 4.43805918 4.4380594  4.43806117 4.43805925 4.43805859 4.43806097
 4.43806187 4.43806098 4.43806102 4.43806297 4.43806353 4.43806446
 4.43806308 4.43806212 4.43806077 4.43805942 4.43805833 4.43805805
 4.43805693 4.4380565  4.43805608 4.43805553 4.43805502 4.43805472
 4.43805465 4.43805469 4.43805474 4.43805476 4.43805477 4.43805475
 4.4380547  4.4380589  4.43805793 4.43805757 4.43805709 4.43805627
 4.43805547 4.43805492 4.43805471 4.4380547  4.43805467 4.43805467
 4.43806026 4.43806183 4.43806337 4.43806479 4.43805535 4.43805511
 4.43805591 4.43805686 4.43805514 4.43805505 4.43805805 4.43805489
 4.43805912 4.43805965 4.43806126 4.43806281 4.43806446 4.43806604
 4.43806667 4.4380674  4.43806528 4.43806691 4.43806877 4.43806903
 4.43806676 4.43806877 4.43806478 4.43806214 4.4380612  4.43806387
 4.43806547 4.43806708 4.43806858 4.43806065 4.43805926 4.4380576
 4.43805635 4.43805602 4.43805603 4.43805578 4.43805814 4.43805731
 4.43805722 4.43805972 4.43805723 4.43806168 4.43806292 4.43806306
 4.43806373 4.43806635 4.438068   4.43806949 4.43807079 4.4380709
 4.43807044 4.43806629 4.43806478 4.43806868 4.43807023 4.43807154
 4.43807251 4.43807226 4.43805938 4.43805878 4.43805868 4.43806223
 4.4380613  4.43806105 4.43806038 4.43806429 4.43806568 4.43806738
 4.43807085 4.43806961 4.43807206 4.43807305 4.43807361 4.43806894
 4.43806695 4.43806606 4.43806402 4.43806326 4.43806579 4.43806836
 4.43806278 4.43806501 4.43806772 4.43807163 4.43807056 4.43807018
 4.43807311 4.43807389 4.43807218 4.43807348 4.43807201 4.4380698
 4.43806788 4.43806596 4.4380637  4.43806125 4.43805899 4.43805686
 4.43805548 4.43805473 4.43805474 4.43805527 4.43805613 4.43805707
 4.43805801 4.43805468 4.43805471 4.43805514 4.43805633 4.43805812
 4.43806013 4.43806243 4.43806508 4.43805497 4.43805564 4.43805638
 4.43805475 4.43805465 4.43805477 4.43805523 4.43805603 4.43805524
 4.43805747 4.43805943 4.43806129 4.43805485 4.43805467 4.4380635
 4.43805467 4.43806739 4.43806558 4.43806958 4.43807117 4.43807273
 4.43807406 4.43807363 4.43807403 4.43807334 4.43807091 4.43807214
 4.43806905 4.43806648 4.43806389 4.43806064 4.43805729 4.4380588
 4.43806901 4.43806693 4.43807079 4.43807298 4.43807187 4.43807392
 4.43807333 4.4380735  4.4380731  4.43807248 4.43807223 4.43807246
 4.43807039 4.43806895 4.43807218 4.4380708  4.43807212 4.43807159
 4.43807061 4.43807031 4.43807098 4.43807071 4.43806953 4.43807121
 4.43807042 4.43807104 4.4380693  4.43806499 4.43806698 4.4380627
 4.43806009 4.43806865 4.43806914 4.43805706 4.43805835 4.43805593
 4.43805496 4.43805467 4.43805527 4.43805476 4.4380563  4.43805753
 4.43805835 4.43805466 4.43805512 4.43805622 4.43805569 4.43805494
 4.4380566  4.43805522 4.43805469 4.43805474 4.43805533 4.43805626
 4.43805751 4.43805976 4.43806185 4.43806438 4.43806649 4.43806706
 4.43806392 4.43806512 4.43806116 4.43806277 4.4380587  4.43805697
 4.43806011 4.43805773 4.43805519 4.43805589 4.43805473 4.43805468
 4.43805602 4.43805513 4.43805742 4.43805946 4.43806182 4.4380548
 4.43805466 4.43805504 4.43805587 4.43805473 4.43805468 4.43805497
 4.43805608 4.43805525 4.4380579  4.43805626 4.43805515 4.43805467
 4.43806041 4.43805833 4.43806415 4.43806245 4.4380666  4.43806899
 4.43807079 4.43807203 4.4380728  4.43807304 4.43807266 4.43807163
 4.43807004 4.43806802 4.43806577 4.43806335 4.43806097 4.43805884
 4.43805707 4.43805575 4.43805491 4.43806106 4.43805695 4.43805578
 4.43805497 4.43805874 4.43805467 4.43805475 4.4380658  4.43806369
 4.43806765 4.43806952 4.43807095 4.43807156 4.43807163 4.43807094
 4.43806968 4.43806795 4.43806591 4.43806374 4.4380615  4.43805941
 4.43805762 4.4380562  4.43805522 4.43805523 4.43805589 4.43805714
 4.43805893 4.4380613  4.43806426 4.43806662 4.43806859 4.43806906
 4.43806849 4.43806575 4.43806714 4.4380668  4.43806289 4.43805995
 4.43805785 4.43805641 4.43806435 4.43806138 4.4380586  4.43805685
 4.43805553 4.43805477 4.43806656 4.43806436 4.43806813 4.43806232
 4.4380695  4.43807017 4.43806949 4.43806969 4.43806873 4.43806732
 4.43806555 4.4380636  4.43806161 4.43805965 4.43805791 4.43805651
 4.43805547 4.43806774 4.43806705 4.43806559 4.43806304 4.43806075
 4.43806551 4.4380636  4.43806132 4.43806836 4.43806714 4.43806534
 4.43806313 4.43806726 4.4380662  4.43806473 4.43806303 4.43806125
 4.43805953 4.43805793 4.4380566  4.43806581 4.43806458 4.43806281
 4.43806461 4.43806353 4.43806212 4.43806057 4.43805814 4.43805662
 4.43806314 4.43806198 4.43805539 4.43806215 4.43806212 4.43806091
 4.43805965 4.43806056 4.43806099 4.43806058 4.43805952 4.43805868
 4.43805899 4.43805885 4.43805843 4.43805697 4.43805554 4.43805486
 4.43805726 4.43805658 4.43805538 4.43805599 4.43805721 4.43805717
 4.43805578 4.43805511 4.43805497 4.43805465 4.43805494 4.43805466
 4.43805598 4.43805752 4.43805935 4.43805512 4.43806186 4.43806421
 4.43805644 4.43805813 4.43805992 4.43806204 4.43806531 4.43806733
 4.43806797 4.43806855 4.43806541 4.43806328 4.43806598 4.43806328
 4.4380687  4.43806871 4.43806642 4.43806375 4.43806661 4.43806616
 4.43806697 4.43806398 4.43806488 4.43806428 4.43806156 4.43805956
 4.4380624  4.43805969 4.43805765 4.43805632 4.4380555  4.43805641
 4.4380576  4.43805501 4.4380557  4.43805649 4.43805533 4.43805477
 4.43805465 4.43805473 4.43805486 4.43805521 4.43805474 4.43805619
 4.43805466 4.43805469 4.43805517 4.43805599 4.43805796 4.43805944
 4.43805738 4.43805488 4.43805591 4.43805706 4.43806012 4.43805897
 4.43805864 4.4380633  4.43806494 4.43806439 4.43806113 4.43806194
 4.43806151 4.43805964 4.43805737 4.43805566 4.43806125 4.43805705
 4.43805894 4.43805493 4.43805466 4.43805486 4.43805563 4.43805548
 4.4380569  4.43805665 4.4380582  4.43805793 4.43805687 4.43805854
 4.43805576 4.43805492 4.43805469 4.43805538 4.43805688 4.43805862
 4.43806025 4.43806109 4.43805934 4.43805875 4.43805712 4.43805576
 4.43805488 4.43805466 4.43805499 4.43805579 4.43805678 4.43805939
 4.43805968 4.43805856 4.43805762 4.43805762 4.43805735 4.43805602
 4.43805545 4.43805489 4.43805465 4.43805609 4.43805621 4.43805599
 4.43805498 4.43805521 4.43805465 4.43805486 4.43805529 4.43805505
 4.43805614 4.43805743 4.43805645 4.43805585 4.43805517 4.43805469
 4.43805523 4.4380549  4.43805486 4.43805522 4.43805465 4.43805473
 4.43805473 4.43805469 4.43805474 4.4380548 ], abun=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Traceback (most recent call last):
  File "C:\Users\NEEL VADODARIA\PycharmProjects\archival_data_collection\venv\lib\site-packages\phoebe\backend\universe.py", line 1817, in _populate_lc
    photon_weighted=intens_weighting=='photon')
  File "C:\Users\NEEL VADODARIA\PycharmProjects\archival_data_collection\venv\lib\site-packages\phoebe\atmospheres\passbands.py", line 2859, in ldint
    raise ValueError('Atmosphere parameters out of bounds: Teff=%s, logg=%s, abun=%s' % (Teff[nanmask], logg[nanmask], abun[nanmask]))`

However the same error does not appear when using a google Collab session.

**Comment by AstroNeel98** [comment]
Hello,

I am running version 2.3.44 of phoebe.
The output of `print(phoebe.get_passband('Johnson:V').timestamp)` is `Sun Dec 22 10:12:21 2019`

I haven't made any changes to the tutorial script, however I am pasting the one I used here for your reference.

```
import phoebe
from phoebe import u # units
import numpy as np
import matplotlib.pyplot as plt

logger = phoebe.logger()

b = phoebe.default_star(starA='sun')
b.set_value('teff', 1.0*u.solTeff)
b.set_value('requiv', 1.0*u.solRad)
b.set_value('mass', 1.0*u.solMass)
b.set_value('period', 24.47*u.d)
print(b['sun'])

b.set_value('incl', 23.5*u.deg)
b.set_value('distance', 1.0*u.AU)

print(b.get_quantity('teff'))
print(b.get_quantity('requiv'))
print(b.get_quantity('mass'))
print(b.get_quantity('period'))
print(b.get_quantity('incl'))
print(b.get_quantity('distance'))

b.add_dataset('lc', times=[0.], pblum=1*u.solLum)
b.add_dataset('mesh', compute_times=[0.], columns=['teffs', 'loggs', 'rs'])

b.run_compute(irrad_method='none', distortion_method='rotstar')

```
Thank you for your help, and sorry for the late response.

**Comment by kecnry** [comment]
This seems to be compiler dependent and you might even find that it happens somewhat randomly. @aprsa has (independently of this report) reproduced the same problem and we are working on a fix.

**Comment by aprsa** [comment]
This bug was caused by an uninitialized value in libphoebe; @horvatm's latest commit fixes it, but it hasn't been propagated to devel yet. @kecnry, we should release this as a bugfix.
