### ISSUE TITLE
Online passband history query not working

### ISSUE THREAD

**Issue by aprsa** [phoebe-project/phoebe2#973]
>>> phoebe.list_passband_online_history("Stromgren:u")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrej/projects/phoebe/phoebe/phoebe/atmospheres/passbands.py", line 2206, in list_passband_online_history
    return {k:v for k,v in all_history.items() if installed_timestamp < _timestamp_to_dt(k)} if installed_timestamp is not None else all_history
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'

**Comment by aprsa** [comment]
[This PR](https://github.com/phoebe-project/phoebe2/pull/979) fixes the history issue and supports ISO timestamps.

**Comment by aprsa** [comment]
The server is still not fully backwards-compatible, investigating.

**Comment by aprsa** [comment]
Fixed by [this PR](https://github.com/phoebe-project/tables.phoebe-project.org/pull/3).
